status: "ready"
context:
  id: "text"
  name: "text"
  label: "Text"
  required: false
  value: ""
  disabled: false
  error: "Please provide a value for this field"
default: "default-light"
variants:
  - name: "default-light"
  - name: "default-dark"
    preview: "@dark"
