status: "ready"
context:
  id: "text"
  name: "text"
  label: "Text"
  required: false
  value: ""
  disabled: false
  error: "Please provide a value for this field"
default: "default-light"
variants:
  - name: "default-light"
    context:
      # Any text format, no checkbox/radio:
      type: "text"
      autocomplete: ""
  - name: "default-dark"
    preview: "@dark"
    context:
      # Any text format, no checkbox/radio:
      type: "text"
      autocomplete: ""
  - name: "multiline-light"
  - name: "multiline-dark"
    preview: "@dark"
